"""add task indexes

Revision ID: 60c53a61a707
Revises: c471a73dad42
Create Date: 2026-06-17 15:19:55.445603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c53a61a707'
down_revision: Union[str, Sequence[str], None] = 'c471a73dad42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tasks_due_date_idx', 'tasks', ['due_date'], unique=False)
    op.create_index('tasks_user_id_idx', 'tasks', ['user_id'], unique=False)
    op.create_index('tasks_user_id_status_idx', 'tasks', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tasks_user_id_status_idx', table_name='tasks')
    op.drop_index('tasks_user_id_idx', table_name='tasks')
    op.drop_index('tasks_due_date_idx', table_name='tasks')
    # ### end Alembic commands ###
